[IEco] Updated sections 1, 2 and 3
leic-pt/resumos-leic pull request #1026
Opened 2024-08-01 11:52 UTC by dcaoc03

Added and developed the following sections of IEco:
- Mercados. Eficiência. Papel do Governo
- PIB e Crescimento Económico, Inovação e Progresso Tecnológico
- Inflação. Desemprego e Desigualdade

I'm planning to update the following four sections as well.
Be sure to look for any typos or other mistakes, I'm open to any feedback.

2024-08-01 22:54 UTC, diogotcorreia requested changes
Found some typos, but overall awesome work, thanks a lot!

Btw, if you want to remove the "Página Incompleta" banner at the top of the pages feel free to do so. I put it there since I wrote these pages in a rush in the day of the exam as self-study.

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0001-mercados-eficiencia-governo.md
> +pessoas e o seu ambiente na produção dos seus meios de subsistência
Missing period (`.`) at end of sentence
```suggestion
pessoas e o seu ambiente na produção dos seus meios de subsistência.
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0001-mercados-eficiencia-governo.md
> +e o Planeamento Económico Centralizado, este último popularizado pela União Soviética no século XX)
Missing period (`.`) at end of sentence
```suggestion
e o Planeamento Económico Centralizado, este último popularizado pela União Soviética no século XX).
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0001-mercados-eficiencia-governo.md
> +  - Quanto maior for o preço, mais as empresas quererão produzir
```suggestion
- A [**curva da oferta**](color:blue) corresponde à quantidade que as empresas estão dispostas a produzir
  por um determinado preço.
  - Quanto maior for o preço, mais as empresas quererão produzir.
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0001-mercados-eficiencia-governo.md
> +É dado pela da área a sombreado na figura
```suggestion
É dado pela da área a sombreado na figura.
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0001-mercados-eficiencia-governo.md
> +A **Economia** é o estudo das interaçações e das trocas estabelecidas entre várias pessoas e entre
```suggestion
A **Economia** é o estudo das interações e das trocas estabelecidas entre várias pessoas e entre
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0001-mercados-eficiencia-governo.md
> +- [**Exitência do Poder de Mercado**](color:orange)
```suggestion
- [**Existência do Poder de Mercado**](color:orange)
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0001-mercados-eficiencia-governo.md
> +3. **Compensação das Partes Afetadas**: pagamento direto de uma indemização aos terceiros envolvidos;
```suggestion
3. **Compensação das Partes Afetadas**: pagamento direto de uma indemnização aos terceiros envolvidos;
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0002-pib-crescimento-economico.md
> +- a abudância de carvão nas colónias.
```suggestion
- a abundância de carvão nas colónias.
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0002-pib-crescimento-economico.md
> +  - pode também haver um aumento do emprego (através de realocação de mão-se-obra, por exemplo).
```suggestion
  - pode também haver um aumento do emprego (através de realocação de mão-de-obra, por exemplo).
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0002-pib-crescimento-economico.md
> +A criação de emprego é altamente **pró-ciclica** (mais procura, mais vagas, mais trabalho), enquanto que a destruição de emprego é **contra-cíclica**.
```suggestion
A criação de emprego é altamente **pró-cíclica** (mais procura, mais vagas, mais trabalho), enquanto que a destruição de emprego é **contra-cíclica**.
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0003-inflacao-desemprego-desigualdade.md
> +**[Índice de Preços no Comsumidor (IPC)](color:red)**: mede o nível geral de preços que os
```suggestion
**[Índice de Preços no Consumidor (IPC)](color:red)**: mede o nível geral de preços que os
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0003-inflacao-desemprego-desigualdade.md
> +3. Aumeto dos salários.
```suggestion
3. Aumento dos salários.
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0002-pib-crescimento-economico.md
> +- **[Co-seguro (Co-insurance)](color:red)**: recorrer a apoios da Segurança Social ou do Governo.
```suggestion
- **[Auto-seguro (_Self-insurance_)](color:yellow)**: poupar dinheiro ou pedir um empréstimo, sacrificando poder de compra futuro;
- **[Co-seguro (_Co-insurance_)](color:red)**: recorrer a apoios da Segurança Social ou do Governo.
```

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0003-inflacao-desemprego-desigualdade.md
>  <!-- TODO consequências inflação e deflação -->
Isn't this done now?

2024-08-01 22:54 UTC, diogotcorreia commented on content/ieco/0003-inflacao-desemprego-desigualdade.md
> +  - População Ativa (Labour Force)´
```suggestion
  - População Ativa (Labour Force)
```

2024-08-02 09:42 UTC, dcaoc03 commented
Thanks for the help! I'll be sure to correct the typos and remove the "Página Incompleta" banner.

2024-08-02 10:14 UTC, diogotcorreia approved these changes

2024-08-02 10:14 UTC, merged