[IEco] Updated sections 4 and 5
leic-pt/resumos-leic pull request #1027
Opened 2024-08-14 18:56 UTC by dcaoc03

Updated the following sections of IEco:

- Bancos. Moeda e o Mercado de Crédito. Crises Financeiras e Globalização
- Política Económica

I'll try to update sections 6 and 7 soon.
Once again, be sure to look for any typos or other mistakes.

2024-08-15 11:11 UTC, diogotcorreia requested changes
Everything else looks good, thanks! (Haven't looked too much into the content itself since it has been a while :sweat_smile: )

2024-08-15 11:11 UTC, diogotcorreia commented on content/ieco/0004-bancos-moeda-crises-financeiras.md
> +- **Imposição de tarifas**: discriminização de produtos estrangeiros.
`discriminização` is not a word, perhaps `discriminação` or `descriminalização`?

2024-08-16 09:48 UTC, dcaoc03 commented
Thanks for the help once again!

2024-08-16 10:20 UTC, diogotcorreia approved these changes

2024-08-16 10:21 UTC, merged