[PE] Joint probability distribution.
leic-pt/resumos-leic pull request #697
Opened 2022-04-27 21:01 UTC by Calhau18

2022-04-27 21:01 UTC, Calhau18 commented
RTM

2022-04-28 11:25 UTC, diogotcorreia commented on content/pe/0005-distribuicoes-conjuntas.md
> +// TODO: Gaspar mete aí cores nos bolds pls
@randomicecube

2022-04-28 11:25 UTC, diogotcorreia commented on content/pe/0005-distribuicoes-conjuntas.md
> +// TODO: INSERIR TABELA
TODO ^

2022-04-28 11:25 UTC, diogotcorreia commented on content/pe/0005-distribuicoes-conjuntas.md
> +// GASPAAAAAAAAAAAAAAR mete as mesmas cores que meteste em cima :fixe2:
@randomicecube :kek:

2022-04-28 11:26 UTC, diogotcorreia requested changes
Still incomplete

2022-04-30 20:22 UTC, diogotcorreia approved these changes

2022-04-30 20:25 UTC, merged