[PE] Fix typos, mistakes, wording, pontuation
leic-pt/resumos-leic pull request #814
Opened 2022-07-02 13:37 UTC by jjasferreira

2022-07-04 20:42 UTC, Pesteves2002 requested changes

2022-07-04 20:42 UTC, Pesteves2002 commented on content/pe/0001-nocoes-basicas.md
> +2. Como $A \cap \overline{A} = \emptyset$, temos, segundo o axioma 3., que $P(A) + P(\overline{A}) = P(A \cup \overline{A}) = P(\Omega) = 1$
Falta retirar o ponto

2022-07-04 20:42 UTC, Pesteves2002 commented on content/pe/0001-nocoes-basicas.md
> +4. Como $A \cap (B \backslash A) = \emptyset$, temos, segundo o axioma 3., que $P(A) + P(B \backslash A) = P(A \cup (B \backslash A)) = P(A \cup B)$. Somando, então, $P(A)$ a ambos os lados da equaçã
Falta retirar o ponto

2022-07-04 20:42 UTC, Pesteves2002 commented on content/pe/0001-nocoes-basicas.md
> +5. Se $A \subset B$, então $A \cup B = A$. Segundo 3., temos então que $P(A) = P(B) - P(B \backslash A) \leq P(B)$ já que $P(B \backslash A) \geq 0$ devido ao axioma 2.
Falta retirar o ponto

2022-07-04 20:42 UTC, Pesteves2002 commented on content/pe/0003-va-discretas.md
> +E(X) = \frac{1}{0.6} ≈ 1.67 \quad \quad V(X) = \frac{0.4}{0.6^2} ≈ 1.11
Porquê aproximado?

2022-07-04 20:42 UTC, Pesteves2002 commented on content/pe/0007-estimacao-pontual.md
> +Definimos a **eficiência relativa** de um estimador $T_1(\underline{X})$ em relação a um estimador $T_2(\underline{X})$ de parâmetro desconhecido $\theta$ como
Devia-se manter os ":"

2022-07-04 20:42 UTC, Pesteves2002 commented
Top, só falta essas pequenas mudanças. THX :prayge:

2022-07-04 21:05 UTC, jjasferreira commented on content/pe/0003-va-discretas.md
> +E(X) = \frac{1}{0.6} ≈ 1.67 \quad \quad V(X) = \frac{0.4}{0.6^2} ≈ 1.11
As frações correspondem a dízimas infinitas. Por exemplo, 1/0.6 = 1.6(6) ≠ 1.67.

2022-07-04 21:33 UTC, diogotcorreia commented on content/pe/0003-va-discretas.md
> +E(X) = \frac{1}{0.6} ≈ 1.67 \quad \quad V(X) = \frac{0.4}{0.6^2} ≈ 1.11
Usem `\approx` em vez do unicode char, é mais reliable

2022-07-04 21:47 UTC, diogotcorreia approved these changes

2022-07-05 09:54 UTC, Pesteves2002 approved these changes

2022-07-05 12:55 UTC, merged