[PE] Add missing content
leic-pt/resumos-leic pull request #823
Opened 2022-07-10 12:56 UTC by randomicecube

Closes #811

2022-07-11 11:12 UTC, Pesteves2002 requested changes

2022-07-11 11:12 UTC, Pesteves2002 commented on content/pe/0003-va-discretas.md
> +:::tip[Motivação]
Muda o warning em cima para danger  para manter conformidade com o resto da distribuicoes q n foram lecionadas

2022-07-11 11:12 UTC, Pesteves2002 commented on content/pe/0009-teste-de-hipoteses.md
> +&= \frac{(10 - 1) \cdot 3.9(3)^{\smartcolor{orange}{*}}}{4} \\
Falta saber onde os asterisco vai dar

2023-11-12 23:30 UTC, diogotcorreia commented
Even though this isn't finished, I'm going to merge it as is. A future PR can be opened to finish the remaining tasks in #811.

2023-11-12 23:34 UTC, diogotcorreia approved these changes

2023-11-13 10:50 UTC, Pesteves2002 requested changes

2023-11-13 10:50 UTC, Pesteves2002 commented on content/pe/0002-variaveis-aleatorias.md
> +  - $V(X^2) = E([X^2]^2) - [E^2(X)]^2 = E(X^4) - E(X)^4$;
```suggestion
  - $V(aX+b) = a^2V(x)$, para $a,b \in \R$;
  - $V(X^2) = E([X^2]^2) - [E^2(X)]^2 = E(X^4) - E(X)^4$.
```

2023-11-13 10:50 UTC, Pesteves2002 commented on content/pe/0003-va-discretas.md
> +Sendo assim, por exemplo, se considerarmos a EA que verifica se o ecrã de um telemóvel se parte no primeiro ano de uso, o sucesso será "o ecrã partiu-se".
```suggestion
Sendo assim, por exemplo, se considerarmos a Experiência $A$ que verifica se o ecrã de um telemóvel se parte no primeiro ano de uso, o sucesso será "o ecrã partiu-se".  
```

2023-11-13 10:59 UTC, Pesteves2002 approved these changes

2023-11-13 10:59 UTC, merged