Add AL
leic-pt/resumos-leic pull request #833
Opened 2022-08-24 14:33 UTC by randomicecube

2022-08-27 18:33 UTC, Pesteves2002 requested changes

2022-08-27 18:33 UTC, Pesteves2002 commented on content/al/0001-introducao.md
> +a_{m1} x_1 + a_{n2} x_2 + \ldots + a_{mn} x_n = b_m
a_{n2} x_2 -> a_{m2} x_2

2022-08-27 18:33 UTC, Pesteves2002 commented on content/al/0001-introducao.md
> +a_{m1} x_1 + a_{n2} x_2 + \ldots + a_{mn} x_n = b_m
a_{n2} x_2 -> a_{m2} x_2

2022-08-27 18:33 UTC, Pesteves2002 commented on content/al/0001-introducao.md
> +a_{m1} & a_{n2} & \ldots & a_{mn}
a_{n2} x_2 -> a_{m2} x_2

2022-08-27 18:33 UTC, Pesteves2002 commented on content/al/0001-introducao.md
> +## Sistemas de Equações Lineares
Sistemas de Equações Lineares (SEL)

2022-08-27 18:33 UTC, Pesteves2002 commented on content/al/0001-introducao.md
> +dois SEL são [**equivalentes**](color:blue) caso os respetivos conjuntos de soluções sejam iguais.
SEL ou SELs?

2022-08-27 18:33 UTC, Pesteves2002 commented on content/al/0001-introducao.md
> +É natural que se tentem encontrar formas de resolver SELs da forma mais eficiente possível:
SEL ou SELs?

2022-08-27 18:33 UTC, Pesteves2002 commented on content/al/0001-introducao.md
> +  Podemos denotar esta operação através de $\alpha L_i$, onde $\alpha$ é o tal número pelo qual estamos a multiplicar a linha.
Neste caso $\alpha = 2$

2022-08-27 18:33 UTC, Pesteves2002 commented on content/al/0001-introducao.md
> +\underrightarrow{L_2 - 2L_1}
Transformação mal feita

 resto do exemplo mal ;(

2022-09-15 21:07 UTC, Pesteves2002 requested changes
Nice job

2022-09-15 21:07 UTC, Pesteves2002 commented on content/al/0003-determinantes.md
> +Colocado em linguagem corrente, a matriz transposta obtém-se trocando as coluna e linha de cada entrada
fix typo: as coluna e linha

2022-09-15 21:07 UTC, Pesteves2002 commented on content/al/0003-determinantes.md
> +Uma matriz dir-se-á simétrica, claro, caso $A = A^T$. A matrizes identidade e nula são exemplos
fix typo: a matrizes

2022-09-16 21:09 UTC, randomicecube commented
@diogotcorreia @Pesteves2002 should be good to go, I'll add more stuff afterwards, will be merged tomorrow if there aren't any other changes requested

2022-09-16 21:16 UTC, Pesteves2002 commented
Amanhã vejo ⚡️

2022-09-17 10:48 UTC, Pesteves2002 commented
LGTM @randomicecube

2022-09-18 15:17 UTC, Pesteves2002 approved these changes

2022-09-18 15:20 UTC, diogotcorreia approved these changes

2022-09-18 22:00 UTC, merged

2022-09-19 12:45 UTC, Pesteves2002 commented
@randomicecube merge it!!!