Add OC content
leic-pt/resumos-leic pull request #847
Opened 2022-10-02 12:11 UTC by constancadcunha

2022-10-16 14:43 UTC, diogotcorreia commented on content/oc/0003-papel-compilador.md
> +description: >-
Missing description

2022-10-16 14:43 UTC, diogotcorreia commented on content/oc/0003-papel-compilador.md
> +# Papel de um computador
Title does not match page name

2022-10-16 14:56 UTC, D-Card commented on content/oc/0003-papel-compilador.md
> +Como podemos ver no gráfico acima, o _miss rate_ sobe quando o tamanho do bloco se uma fração mais significativa do tamanho da cache visto que o número de bloco que pode ser contido no mesmo tamanho
Missing words?

2022-10-16 15:10 UTC, D-Card requested changes

2022-10-16 15:10 UTC, D-Card commented on content/oc/0003-papel-compilador.md
> +Antes de começarmos temos que relembrar a [diferença entre o CPU e RAM](color:purple). O RAM é a memória, o processador faz os cálculos/computações. Basicamente se tivermos um carpinteiro atrabalhar
```suggestion
Antes de falar de memória é importante distinguir a [diferença entre o CPU e RAM](color:purple). A RAM é a memória primária enquanto que o processador faz os cálculos/computações. Pegando num exemplo, se tivermos um carpinteiro a arranjar uma cadeira e este tiver uma caixa com ferramentas, num dado momento só um certo número de ferramentas é que está a ser usado para consertar a cadeira. Estas ferramentas encontrar-se-ão mais próximo do carpinteiro, por exemplo no seu cinto, enquanto o resto estará na caixa. Usar as ferramentas que estão no seu cinto é mais rápido do que tirar uma ferramenta da caixa e usá-la. Se o carpinteiro for esperto, irá ter no seu cinto as ferramentas que precisa mais frequentemente para a tarefa que está a fazer no momento e deixará na caixa as ferramentas menos utilizadas. Assim, aplicando esta analogia a um computador, o [carpinteiro é o CPU](color:red), as [ferramentas que estão no cinto são a RAM](color:pink) e [as ferramentas que estão na caixa são o disco rígido](color:purple).
```

2022-10-16 23:00 UTC, D-Card requested changes

2022-10-18 16:05 UTC, diogotcorreia approved these changes

2022-10-18 16:05 UTC, merged