[RC] Overall fix on all course pages
leic-pt/resumos-leic pull request #934
Opened 2023-01-30 18:17 UTC by jjasferreira

- Fix typos and punctuation;
- Improve wording and cohesion;
- Change some text style;
- Correct verb conjugations and gender of pronouns/noun determiners;
- Add a few tidbits.

2023-02-01 22:40 UTC, diogotcorreia requested changes
Everything else looks great, thank you a lot!

I'll the comments unresolved in case you want to discuss some of them, otherwise resolve them and I'll merge the PR :)

2023-02-01 22:40 UTC, diogotcorreia commented on content/rc/0003-transporte.md
> +- no caso do pacote não ter sido bem recebidO, o emissor reenvia o pacote, após ter recebido o NAK.
```suggestion
- no caso do pacote não ter sido bem recebido, o emissor reenvia o pacote, após ter recebido o NAK.
```

2023-02-01 22:40 UTC, diogotcorreia commented on content/rc/0003-transporte.md
> +(visto que se assume que esta se manteve) e quando mais perto estivermos, mais lentamente nos aproximamos.
```suggestion
(visto que se assume que esta se manteve) e quanto mais perto estivermos, mais lentamente nos aproximamos.
```

2023-02-01 22:40 UTC, diogotcorreia commented on content/rc/0003-transporte.md
> +foi criado o protocolo **QUIC** (_Quick UDP Internet Connections_), inventada pela Google.
```suggestion
foi criado o protocolo **QUIC** (_Quick UDP Internet Connections_), inventado pela Google.
```

2023-02-01 22:40 UTC, diogotcorreia commented on content/rc/0004-rede.md
> +a.b.c.d /n
```suggestion
a.b.c.d/n
```

I don't think I've ever seen CIDR notation with spaces :thinking: 
Neither `ip -c a` nor [Wikipedia](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) have spaces in the CIDR representation of IP addresses.

2023-02-01 22:40 UTC, diogotcorreia commented on content/rc/0004-rede.md
> +e os 8 bits restantes representam o _host_, podendo tudo ser representado da forma `123.221.222.68 /24`.
```suggestion
e os 8 bits restantes representam o _host_, podendo tudo ser representado da forma `123.221.222.68/24`.
```

Same here

2023-02-01 22:40 UTC, diogotcorreia commented on content/rc/0005-ligacao-dados.md
> +  .
```suggestion
- Passagem de um _token_.
```

Probably an accidental line break

2023-02-02 00:44 UTC, jjasferreira commented
> Everything else looks great, thank you a lot!
> 
> I'll the comments unresolved in case you want to discuss some of them, otherwise resolve them and I'll merge the PR :)

Thank you for reviewing this!
You're absolutely right about the CIDR notation. 😃

2023-02-02 00:48 UTC, diogotcorreia approved these changes

2023-02-02 00:48 UTC, merged